export interface Asset {
    ticker: string;
    name: string;
    price: string;
    variation: string;
    sector: string;
    exchange: string;
    sentiment: number;
    bullCase: { title: string; desc: string }[];
    bearCase: { title: string; desc: string }[];
    fullReport?: string;
    logo?: string;
    size?: number;
    cgId?: string;
    aiPulse?: string;
    marketCap?: string;
    peRatio?: string;
    dividendYield?: string;
    lastUpdate?: string;
    deepResearchText?: string;
    reportHtmlContent?: string;
    reportHtmlPath?: string;
    type?: string;
    vacancia?: string;
    sharesOutstanding?: number;
    netAssets?: number;
    taxaAdm?: string;
    expenseRatio?: string;
    benchmark?: string;
    avgVolume?: number;
    tvl?: string;
    networkActivity?: string;
    tokenInflation?: string;
    networkRevenue?: string;
    onChainScore?: number;
}

/**
 * Normaliza tickers para que o cache seja consistente entre as telas (Mercado, Ticker, Portfolio).
 * Remove sufixos como .SA e -USD e converte para minúsculas.
 */
export const normalizeTickerForCache = (ticker: string | undefined): string => {
    if (!ticker || typeof ticker !== 'string') return "unknown";
    return ticker.toLowerCase().replace('.sa', '').replace('-usd', '').replace('usd', '').trim();
};

export const b3Assets: Asset[] = [
    {
        ticker: "MXRF11.SA",
        type: "Fundo Imobiliário",
        name: "Maxi Renda FII",
        price: "0.00",
        variation: "0.0",
        sector: "Fundos Imobiliários",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=xpi.com.br&sz=128",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "03/04/2026"
    },
    {
        ticker: "ABEV3.SA",
        type: "Ações",
        name: "Ambev SA",
        price: "0.00",
        variation: "0.0",
        sector: "Consumo de Não Duráveis",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.ambev.com.br&sz=128",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ALOS3.SA",
        type: "Ações",
        name: "Allos S.A.",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=allos.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ALUP3.SA",
        type: "Ações",
        name: "Alupar Investimento SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=alupar.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ARND3.SA",
        type: "Ações",
        name: "Arandu Investimentos S.A",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Comerciais",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=aranduinvestimentos.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ASAI3.SA",
        type: "Ações",
        name: "Sendas Distribuidora SA",
        price: "0.00",
        variation: "0.0",
        sector: "Comércio de Varejo",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=assai.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "AZUL53.SA",
        type: "Ações",
        name: "AZUL ON P N2",
        price: "0.00",
        variation: "0.0",
        sector: "Transporte e Logística",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.voeazul.com.br&sz=128",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "B3SA3.SA",
        type: "Ações",
        name: "B3 SA - Brasil, Bolsa, Balcao",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=b3.com.br&sz=128",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "BBAS3.SA",
        type: "Ações",
        name: "Banco do Brasil S.A.",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=bb.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "BBDC3.SA",
        type: "Ações",
        name: "Banco Bradesco SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=bradesco.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "BBSE3.SA",
        type: "Ações",
        name: "BB Seguridade Participacoes SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=bbseguridaderi.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "BEEF3.SA",
        type: "Ações",
        name: "Minerva S.A.",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços de Distribuição",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=minervafoods.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "BPAC3.SA",
        type: "Ações",
        name: "Banco BTG Pactual SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.btgpactual.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },


    {
        ticker: "BRBI11.SA",
        type: "Ações",
        name: "BR Partners Banco de Investimento S.A.",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=brpartners.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },

    {
        ticker: "MOTV3.SA",
        type: "Ações",
        name: "Motiva SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços de Transporte",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=motiva.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },

    {
        ticker: "CMIG3.SA",
        type: "Ações",
        name: "Cia Energetica de Minas Gerais - CEMIG",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.cemig.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "CMIN3.SA",
        type: "Ações",
        name: "CSN Mineracao SA",
        price: "0.00",
        variation: "0.0",
        sector: "Minerais Não Energéticos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.csnmineracao.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "COGN3.SA",
        type: "Ações",
        name: "Cogna Educacao",
        price: "0.00",
        variation: "0.0",
        sector: "Consumo de Serviços",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.cogna.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "CPFE3.SA",
        type: "Ações",
        name: "CPFL Energia SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.cpfl.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "CPLE3.SA",
        type: "Ações",
        name: "Cia Paranaense de Energia - COPEL",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.copel.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "CSAN3.SA",
        type: "Ações",
        name: "Cosan SA",
        price: "0.00",
        variation: "0.0",
        sector: "Energia e Logística",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.cosan.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "CSMG3.SA",
        type: "Ações",
        name: "Cia de Saneamento de Minas Gerais - COPASA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.copasa.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "CSNA3.SA",
        type: "Ações",
        name: "Cia Siderurgica Nacional - CSN",
        price: "0.00",
        variation: "0.0",
        sector: "Minerais Não Energéticos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.csn.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "CURY3.SA",
        type: "Ações",
        name: "Cury Construtora e Incorporadora SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.cury.net&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "CXSE3.SA",
        type: "Ações",
        name: "Caixa Seguridade Participações S.A.",
        price: "0.00",
        variation: "0.0",
        sector: "Seguros",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.caixaseguridade.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "CYRE3.SA",
        type: "Ações",
        name: "Cyrela Brazil Realty SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.cyrela.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "DIRR3.SA",
        type: "Ações",
        name: "Direcional Engenharia SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.direcional.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ECOR3.SA",
        type: "Ações",
        name: "Ecorodovias Infraestrutura e Logistica SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços de Transporte",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.ecorodovias.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "EGIE3.SA",
        type: "Ações",
        name: "Engie Brasil Energia SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=engie.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "AXIA3.SA",
        type: "Ações",
        name: "AXIA Energia SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.axia.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "EMBJ3.SA",
        type: "Ações",
        name: "Embraer SA",
        price: "0.00",
        variation: "0.0",
        sector: "Transporte Eletrônico",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.embraer.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ENEV3.SA",
        type: "Ações",
        name: "Eneva SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.eneva.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ENGI3.SA",
        type: "Ações",
        name: "Energisa SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.energisa.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ENMT3.SA",
        type: "Ações",
        name: "Energisa Mato Grosso SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.energisa.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "EQPA3.SA",
        type: "Ações",
        name: "Equatorial Energia Para SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=equatorialenergia.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "EQTL3.SA",
        type: "Ações",
        name: "Equatorial Energia SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=equatorialenergia.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "EVEN3.SA",
        type: "Ações",
        name: "Even Construtora e Incorporadora SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.even.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "EZTC3.SA",
        type: "Ações",
        name: "EZTEC Empreendimentos e Participacoes SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.eztec.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "FLRY3.SA",
        type: "Ações",
        name: "Fleury SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços de Saúde",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.fleury.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "GGBR3.SA",
        type: "Ações",
        name: "Gerdau SA",
        price: "0.00",
        variation: "0.0",
        sector: "Minerais Não Energéticos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.gerdau.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "GOAU3.SA",
        type: "Ações",
        name: "Metalurgica Gerdau SA",
        price: "0.00",
        variation: "0.0",
        sector: "Minerais Não Energéticos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.gerdau.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "HAPV3.SA",
        type: "Ações",
        name: "Hapvida Participacoes e Investimentos SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços de Saúde",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.hapvida.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "HYPE3.SA",
        type: "Ações",
        name: "Hypera SA",
        price: "0.00",
        variation: "0.0",
        sector: "Tecnologia em Saúde",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.hypera.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "IGTI3.SA",
        type: "Ações",
        name: "Iguatemi SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.iguatemi.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ITSA3.SA",
        type: "Ações",
        name: "Itausa SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=itausa.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ITUB3.SA",
        type: "Ações",
        name: "Itaú Unibanco Holding SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=itau.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "JBSS32.SA",
        type: "Ações",
        name: "JBS SA",
        price: "0.00",
        variation: "0.0",
        sector: "Consumo de Não Duráveis",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=jbs.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "JHSF3.SA",
        type: "Ações",
        name: "JHSF Participacoes SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=jhsf.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "KLBN3.SA",
        type: "Ações",
        name: "Klabin SA",
        price: "0.00",
        variation: "0.0",
        sector: "Indústrias de Processamento",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=klabin.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "LAVV3.SA",
        type: "Ações",
        name: "Lavvi Empreendimentos e Participacoes SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.lavvi.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "LREN3.SA",
        type: "Ações",
        name: "Lojas Renner SA",
        price: "0.00",
        variation: "0.0",
        sector: "Comércio de Varejo",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=lojasrenner.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "MGLU3.SA",
        type: "Ações",
        name: "Magazine Luiza SA",
        price: "0.00",
        variation: "0.0",
        sector: "Comércio de Varejo",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=magazineluiza.com.br&sz=128",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "MBRF3.SA",
        type: "Ações",
        name: "Marfrig Global Foods SA",
        price: "0.00",
        variation: "0.0",
        sector: "Consumo de Não Duráveis",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.marfrig.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "MRVE3.SA",
        type: "Ações",
        name: "MRV Engenharia e Participacoes SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.mrv.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "MTRE3.SA",
        type: "Ações",
        name: "Mitre Engenharia e Participacoes SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=mitrerealty.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "MULT3.SA",
        type: "Ações",
        name: "Multiplan Empreendimentos Imobiliarios SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=multiplan.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "NEOE3.SA",
        type: "Ações",
        name: "Neoenergia SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.neoenergia.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "NATU3.SA",
        type: "Ações",
        name: "Natura &Co Holding SA",
        price: "0.00",
        variation: "0.0",
        sector: "Consumo de Não Duráveis",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.naturaeco.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ODPV3.SA",
        type: "Ações",
        name: "Odontoprev SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços de Saúde",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=odontoprev.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "PETR4.SA",
        type: "Ações",
        name: "Petroleo Brasileiro SA - PETROBRAS (PREF)",
        price: "0.00",
        variation: "0.0",
        sector: "Energia e Logística",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=petrobras.com.br&sz=128",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "PRIO3.SA",
        type: "Ações",
        name: "Petrio SA",
        price: "0.00",
        variation: "0.0",
        sector: "Energia e Logística",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=prio3.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "PSSA3.SA",
        type: "Ações",
        name: "Porto Seguro SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.portoseguro.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "RADL3.SA",
        type: "Ações",
        name: "Raia Drogasil SA",
        price: "0.00",
        variation: "0.0",
        sector: "Comércio de Varejo",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=rdsaude.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "RAIL3.SA",
        type: "Ações",
        name: "Rumo SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços de Transporte",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=rumolog.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "RDOR3.SA",
        type: "Ações",
        name: "Rede D'Or São Luiz SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços de Saúde",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=rededorsaoluiz.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "27/03/2026"
    },
    {
        ticker: "RENT3.SA",
        type: "Ações",
        name: "Localiza Rent a Car SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=localiza.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "SANB3.SA",
        type: "Ações",
        name: "Banco Santander Brasil SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=santander.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "SAPR3.SA",
        type: "Ações",
        name: "Cia de Saneamento do Parana - SANEPAR",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.sanepar.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "SBSP3.SA",
        type: "Ações",
        name: "Cia de Saneamento Basico do Estado de Sao Paulo - SABESP",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=sabesp.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "SUZB3.SA",
        type: "Ações",
        name: "Suzano SA",
        price: "0.00",
        variation: "0.0",
        sector: "Indústrias de Processamento",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=suzano.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "TAEE3.SA",
        type: "Ações",
        name: "Transmissora Alianca de Energia Eletrica SA - TAESA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.taesa.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "TIMS3.SA",
        type: "Ações",
        name: "TIM SA",
        price: "0.00",
        variation: "0.0",
        sector: "Comunicações",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.tim.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "TOTS3.SA",
        type: "Ações",
        name: "Totvs SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços de Tecnologia",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=totvs.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "TPIS3.SA",
        type: "Ações",
        name: "Triunfo Participacoes e Investimentos SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços de Transporte",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=www.triunfo.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "TRIS3.SA",
        type: "Ações",
        name: "Trisul SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=trisul-sa.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },


    {
        ticker: "UGPA3.SA",
        type: "Ações",
        name: "Ultrapar Participacoes SA",
        price: "0.00",
        variation: "0.0",
        sector: "Energia e Logística",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.ultra.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "USIM3.SA",
        type: "Ações",
        name: "Usinas Siderurgicas de Minas Gerais SA - USIMINAS",
        price: "0.00",
        variation: "0.0",
        sector: "Minerais Não Energéticos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=usiminas.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "VALE3.SA",
        type: "Ações",
        name: "Vale SA",
        price: "0.00",
        variation: "0.0",
        sector: "Minerais Não Energéticos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=vale.com&sz=128",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "VIVT3.SA",
        type: "Ações",
        name: "Telefonica Brasil SA",
        price: "0.00",
        variation: "0.0",
        sector: "Comunicações",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=telefonica.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "WEGE3.SA",
        type: "Ações",
        name: "WEG SA",
        price: "0.00",
        variation: "0.0",
        sector: "Produtor Manufatureiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=weg.net&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "YDUQ3.SA",
        type: "Ações",
        name: "YDUQS Participacoes SA",
        price: "0.00",
        variation: "0.0",
        sector: "Consumo de Serviços",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=yduqs.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "AURO11.SA",
        type: "ETFs",
        name: "BUENA VISTA NEOS GOLD HIGH INCOME INDEX FUNDO DE ÍNDICE DE RESPONSABILIDADE LIMITADA",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "AUVP11.SA",
        type: "ETFs",
        name: "BTG Pactual TEVA AUVP Ações Fundamentos",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "BBOI11.SA",
        type: "ETFs",
        name: "BB ETF ÍNDICE FUTURO DE BOI GORDO B3",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "BOVB11.SA",
        type: "ETFs",
        name: "ETF BRADESCO IBOVESPA FDO DE INDICE",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "CMDB11.SA",
        type: "ETFs",
        name: "BTG Pactual Teva Ações Commodities Brasil FDI",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "DEBB11.SA",
        type: "ETFs",
        name: "BTG PACTUAL TEVA DEBÊNTURES DI FUNDO DE ÍNDICE",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "DOLA11.SA",
        type: "ETFs",
        name: "BB ETF Índice Futuro de Dólar S&P/B3 Fundo de Índice",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ESGB11.SA",
        type: "ETFs",
        name: "BTG PACTUAL ESG FUNDO DE ÍNDICE S&P/B3 BRAZIL ES",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "FIXA11.SA",
        type: "ETFs",
        name: "Renda Fixa Pré Índice Futuro de Taxas de Juros S&P/B3",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "JOGO11.SA",
        type: "ETFs",
        name: "Investo ETF GL VI GA & ES Fundo Investimento De Índice IE",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "LVOL11.SA",
        type: "ETFs",
        name: "NU IBOV SMART LOW VOLATILITY B3",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "NTNS11.SA",
        type: "ETFs",
        name: "INVESTO TEVA TESOURO IPCA+ 0 A 4 ANOS ETF – FUNDO DE INVESTIMENTO DE ÍNDICE",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "PACB11.SA",
        type: "ETFs",
        name: "BTG PACTUAL TEVA TESOURO IPCA ULTRA LONGO CE FUNDO DE ÍNDICE",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "SPXB11.SA",
        type: "ETFs",
        name: "BTG PACTUAL S&P 500 FUNDO DE ÍNDICE",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "TIRB11.SA",
        type: "ETFs",
        name: "BTG PACTUAL TEVA DIVIDENDOS ATIVOS REAIS LISTADOS FUNDO DE ÍNDICE",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "UTLL11.SA",
        type: "ETFs",
        name: "INVESTO B3 UTILIDADE PÚBLICA FUNDO DE ÍNDICE",
        price: "0.00",
        variation: "0.0",
        sector: "ETF",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/b3.com.br.ico",
        size: 10,
        cgId: "",
        aiPulse: "Acompanha índice de mercado.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "XPML11.SA",
        type: "FIIs",
        name: "XP Malls Fundo de Investimento Imobiliário - FII",
        price: "0.00",
        variation: "0.0",
        sector: "Fundos Imobiliários",
        exchange: "B3",
        sentiment: 50,
        bullCase: [
            { title: "Portfólio Premium", desc: "Composição baseada em shoppings de alta performance e dominantes." },
            { title: "Poder de Preço", desc: "Capacidade de repasse inflacionário nos aluguéis." }
        ],
        bearCase: [
            { title: "Risco Macroeconômico", desc: "Sensibilidade a juros altos que impactam o consumo." },
            { title: "Vacância", desc: "Possíveis mudanças no comportamento do consumidor pós-pandemia." }
        ],
        logo: "https://www.google.com/s2/favicons?domain=xpinc.com&sz=128",
        size: 15,
        cgId: "",
        aiPulse: "FII de shoppings com foco em ativos de alta qualidade.",
        marketCap: "4B",
        peRatio: "--",
        dividendYield: "9.5%",
        vacancia: "3.5%",
        lastUpdate: "14/03/2026"
    },
    {
        ticker: "BTLG11.SA",
        type: "FIIs",
        name: "BTG Pactual Logística",
        price: "104.01",
        variation: "0.0",
        sector: "Fundos Imobiliários",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=btlg.btgpactual.com&sz=128",
        size: 15,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "3.5B",
        peRatio: "--",
        dividendYield: "9.0%",
        lastUpdate: new Date().toLocaleDateString('pt-BR')
    },
    {
        ticker: "BTAL11.SA",
        type: "FIIs",
        name: "BTG Pactual Agro Logística",
        price: "95.00",
        variation: "0.0",
        sector: "Fundos Imobiliários",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=btgpactual.com&sz=128",
        size: 15,
        cgId: "",
        aiPulse: "Focado em infraestrutura logística para o agronegócio.",
        marketCap: "1.2B",
        peRatio: "--",
        dividendYield: "12.5%",
        lastUpdate: new Date().toLocaleDateString('pt-BR')
    },
    {
        ticker: "VBBR3.SA",
        type: "Ações",
        name: "Vibra Energia SA",
        price: "0.00",
        variation: "0.0",
        sector: "Energia",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.vibraenergia.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "CCRO3.SA",
        type: "Ações",
        name: "CCR SA",
        price: "0.00",
        variation: "0.0",
        sector: "Transporte e Logística",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.ccr.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "BRFS3.SA",
        type: "Ações",
        name: "BRF SA",
        price: "0.00",
        variation: "0.0",
        sector: "Consumo de Não Duráveis",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.brf-global.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "RAIZ4.SA",
        type: "Ações",
        name: "Raizen SA",
        price: "0.00",
        variation: "0.0",
        sector: "Energia e Logística",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.raizen.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "CVCB3.SA",
        type: "Ações",
        name: "CVC Brasil Operadora e Agencia de Viagens SA",
        price: "0.00",
        variation: "0.0",
        sector: "Consumo de Serviços",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.cvc.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ISAE3.SA",
        type: "Ações",
        name: "ISA Energia Brasil SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=isaenergiabrasil.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "20/03/2026"
    },
    {
        ticker: "CGAS5.SA",
        type: "Ações",
        name: "Cia de Gas de Sao Paulo - COMGAS",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.comgas.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "REDE3.SA",
        type: "Ações",
        name: "Rede Energia Participacoes SA",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=energisa.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ARZZ3.SA",
        type: "Ações",
        name: "Arezzo Industria e Comercio SA",
        price: "0.00",
        variation: "0.0",
        sector: "Consumo de Não Duráveis",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.arezzo.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "MRSA3B.SA",
        type: "Ações",
        name: "MRS Logística S.A.",
        price: "0.00",
        variation: "0.0",
        sector: "Transporte e Logística",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=mrs.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "CEGR3.SA",
        type: "Ações",
        name: "Cia Distribuidora de Gas do Rio de Janeiro - CEG",
        price: "0.00",
        variation: "0.0",
        sector: "Serviços Públicos",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=naturgy.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "MDIA3.SA",
        type: "Ações",
        name: "M. Dias Branco SA Indústria e Comércio de Alimentos",
        price: "0.00",
        variation: "0.0",
        sector: "Consumo de Não Duráveis",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.mdiasbranco.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "PLPL3.SA",
        type: "Ações",
        name: "Plano & Plano Desenvolvimento Imobiliario SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.planoeplano.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "TEND3.SA",
        type: "Ações",
        name: "Construtora Tenda SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.tenda.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "MDNE3.SA",
        type: "Ações",
        name: "Moura Dubeux Engenharia SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.mouradubeux.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "MELK3.SA",
        type: "Ações",
        name: "Melnick Desenvolvimento Imobiliario SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.melnick.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "GFSA3.SA",
        type: "Ações",
        name: "Gafisa SA",
        price: "0.00",
        variation: "0.0",
        sector: "Financeiro",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.gafisa.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "PRNR3.SA",
        type: "Ações",
        name: "Priner Serviços Industriais S.A.",
        price: "0.00",
        variation: "0.0",
        sector: "Bens Industriais / Engenharia",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=ri.priner.com.br&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "29/03/2026"
    },
    {
        ticker: "VULC3.SA",
        type: "Ações",
        name: "Vulcabras S.A.",
        price: "0.00",
        variation: "0.0",
        sector: "Consumo Cíclico / Calçados",
        exchange: "B3",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://www.google.com/s2/favicons?domain=vulcabrasri.com&sz=128",
        size: 10,
        cgId: "",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "31/03/2026"
    },
];

export const cryptoAssets: Asset[] = [
    {
        ticker: "BTC-USD",
        name: "Bitcoin",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 82,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/bitcoin.org.ico",
        size: 25,
        cgId: "bitcoin",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "1.3T",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026",
        tvl: "N/A (Layer 1 Base)",
        networkActivity: "Altíssima (> 1M Endereços/Dia)",
        tokenInflation: "0.85% ao ano (Pós-Halving)",
        networkRevenue: "US$ 30 Milhões/mês (Taxas de Mineração)",
        onChainScore: 95
    },
    {
        ticker: "ETH-USD",
        name: "Ethereum",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/ethereum.org.ico",
        size: 25,
        cgId: "ethereum",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "400B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026",
        tvl: "US$ 50 Bilhões",
        networkActivity: "Alta (Líder em Contratos)",
        tokenInflation: "-0.1% ao ano (Deflacionário)",
        networkRevenue: "US$ 150 Milhões/mês",
        onChainScore: 90
    },
    {
        ticker: "ONDO-USD",
        name: "Ondo Finance",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas (RWA)",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/ondo.finance.ico",
        size: 20,
        cgId: "ondo-finance",
        aiPulse: "Líder em RWA (Real World Assets).",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ROSE-USD",
        name: "Oasis Network",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas (Privacidade)",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/oasisprotocol.org.ico",
        size: 20,
        cgId: "oasis-network",
        aiPulse: "Blockchain focada em privacidade.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "LINK-USD",
        name: "Chainlink",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas (Oráculos)",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/chain.link.ico",
        size: 20,
        cgId: "chainlink",
        aiPulse: "Líder em redes de oráculos descentralizados.",
        marketCap: "--",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },


    {
        ticker: "USDT-USD",
        name: "Tether",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/tether.to.ico",
        size: 25,
        cgId: "tether",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "100B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "BNB-USD",
        name: "Binance Coin",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/binance.com.ico",
        size: 25,
        cgId: "binancecoin",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "90B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "SOL-USD",
        name: "Solana",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/solana.com.ico",
        size: 25,
        cgId: "solana",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "65B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026",
        tvl: "US$ 4.5 Bilhões",
        networkActivity: "Extrema (Líder em Transações)",
        tokenInflation: "5.2% ao ano (Decrescente)",
        networkRevenue: "US$ 25 Milhões/mês",
        onChainScore: 82
    },
    {
        ticker: "XRP-USD",
        name: "XRP",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/ripple.com.ico",
        size: 25,
        cgId: "ripple",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "35B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "USDC-USD",
        name: "USDC",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/circle.com.ico",
        size: 25,
        cgId: "usd-coin",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "32B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ADA-USD",
        name: "Cardano",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/cardano.org.ico",
        size: 25,
        cgId: "cardano",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "18B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "AVAX-USD",
        name: "Avalanche",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/avax.network.ico",
        size: 25,
        cgId: "avalanche-2",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "15B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "DOGE-USD",
        name: "Dogecoin",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/dogecoin.com.ico",
        size: 25,
        cgId: "dogecoin",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "22B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "DOT-USD",
        name: "Polkadot",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/polkadot.network.ico",
        size: 25,
        cgId: "polkadot",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "10B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "TRX-USD",
        name: "TRON",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/tron.network.ico",
        size: 25,
        cgId: "tron",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "11B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"

    },
    {
        ticker: "MATIC-USD",
        name: "Polygon",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/polygon.technology.ico",
        size: 25,
        cgId: "matic-network",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "8B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "SHIB-USD",
        name: "Shiba Inu",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/shibatoken.com.ico",
        size: 25,
        cgId: "shiba-inu",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "15B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "LTC-USD",
        name: "Litecoin",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/litecoin.org.ico",
        size: 25,
        cgId: "litecoin",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "6B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "DAI-USD",
        name: "Dai",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/makerdao.com.ico",
        size: 25,
        cgId: "dai",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "5B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "BCH-USD",
        name: "Bitcoin Cash",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/bitcoincash.org.ico",
        size: 25,
        cgId: "bitcoin-cash",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "9B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "UNI-USD",
        name: "Uniswap",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/uniswap.org.ico",
        size: 25,
        cgId: "uniswap",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "8B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "LEO-USD",
        name: "LEO Token",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/bitfinex.com.ico",
        size: 25,
        cgId: "leo-token",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "5B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "NEAR-USD",
        name: "NEAR Protocol",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/near.org.ico",
        size: 25,
        cgId: "near",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "7B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "OP-USD",
        name: "Optimism",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/optimism.io.ico",
        size: 25,
        cgId: "optimism",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "4B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "ARB-USD",
        name: "Arbitrum",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/arbitrum.io.ico",
        size: 25,
        cgId: "arbitrum",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "3B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "APT-USD",
        name: "Aptos",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/aptosfoundation.org.ico",
        size: 25,
        cgId: "aptos",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "4B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "SUI-USD",
        name: "Sui",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/sui.io.ico",
        size: 25,
        cgId: "sui",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "3B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "KAS-USD",
        name: "Kaspa",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/kaspa.org.ico",
        size: 25,
        cgId: "kaspa",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "4B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "PEPE-USD",
        name: "Pepe",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/pepe.vip.ico",
        size: 25,
        cgId: "pepe",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "3B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "WIF-USD",
        name: "dogwifhat",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/dogwifcoin.org.ico",
        size: 25,
        cgId: "dogwifhat",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "2B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "BONK-USD",
        name: "Bonk",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/bonkcoin.com.ico",
        size: 25,
        cgId: "bonk",
        aiPulse: "Análise automatizada pendente.",
        marketCap: "1B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "10/03/2026"
    },
    {
        ticker: "RENDER-USD",
        name: "Render Network",
        price: "0.00",
        variation: "0.0",
        sector: "Criptomoedas (IA/DePIN)",
        exchange: "Crypto Market",
        sentiment: 50,
        bullCase: [],
        bearCase: [],
        logo: "https://icons.duckduckgo.com/ip3/rendernetwork.com.ico",
        size: 25,
        cgId: "render-token",
        aiPulse: "Infraestrutura de computação GPU descentralizada para IA e renderização.",
        marketCap: "2.5B",
        peRatio: "--",
        dividendYield: "--",
        lastUpdate: "29/03/2026"
    },
];

export const sp500Assets: Asset[] = [
    { ticker: "AAPL", name: "Apple Inc.", price: "0.00", variation: "0.0", sector: "Tecnologia", exchange: "NASDAQ", sentiment: 50, bullCase: [], bearCase: [], logo: "https://www.google.com/s2/favicons?domain=apple.com&sz=128" },
    { ticker: "AMZN", name: "Amazon.com Inc.", price: "0.00", variation: "0.0", sector: "Consumo", exchange: "NASDAQ", sentiment: 50, bullCase: [], bearCase: [], logo: "https://www.google.com/s2/favicons?domain=amazon.com&sz=128" },
    { ticker: "MSFT", name: "Microsoft Corp.", price: "0.00", variation: "0.0", sector: "Tecnologia", exchange: "NASDAQ", sentiment: 50, bullCase: [], bearCase: [], logo: "https://www.google.com/s2/favicons?domain=microsoft.com&sz=128" },
    { ticker: "NVDA", name: "NVIDIA Corp.", price: "0.00", variation: "0.0", sector: "Semicondutores", exchange: "NASDAQ", sentiment: 50, bullCase: [], bearCase: [], logo: "https://www.google.com/s2/favicons?domain=nvidia.com&sz=128" },
    { ticker: "GOOGL", name: "Alphabet Inc.", price: "0.00", variation: "0.0", sector: "Tecnologia", exchange: "NASDAQ", sentiment: 50, bullCase: [], bearCase: [], logo: "https://www.google.com/s2/favicons?domain=abc.xyz&sz=128" },
    { ticker: "META", name: "Meta Platforms Inc.", price: "0.00", variation: "0.0", sector: "Tecnologia", exchange: "NASDAQ", sentiment: 50, bullCase: [], bearCase: [], logo: "https://www.google.com/s2/favicons?domain=facebook.com&sz=128" },
    { ticker: "TSLA", name: "Tesla Inc.", price: "0.00", variation: "0.0", sector: "Automotivo", exchange: "NASDAQ", sentiment: 50, bullCase: [], bearCase: [], logo: "https://www.google.com/s2/favicons?domain=tesla.com&sz=128" },
    { ticker: "KO", name: "Coca-Cola Co.", price: "0.00", variation: "0.0", sector: "Consumo", exchange: "NYSE", sentiment: 50, bullCase: [], bearCase: [], logo: "https://www.google.com/s2/favicons?domain=cocacola.com&sz=128" },
    { ticker: "WMT", name: "Walmart Inc.", price: "0.00", variation: "0.0", sector: "Consumo", exchange: "NYSE", sentiment: 50, bullCase: [], bearCase: [], logo: "https://www.google.com/s2/favicons?domain=walmart.com&sz=128" },
    { ticker: "CVX", name: "Chevron Corp.", price: "0.00", variation: "0.0", sector: "Energia", exchange: "NYSE", sentiment: 50, bullCase: [], bearCase: [], logo: "https://www.google.com/s2/favicons?domain=chevron.com&sz=128" },
    { ticker: "NKE", name: "Nike Inc.", price: "0.00", variation: "0.0", sector: "Consumo", exchange: "NYSE", sentiment: 50, bullCase: [], bearCase: [], logo: "https://www.google.com/s2/favicons?domain=nike.com&sz=128" },
];

export const originalAssets: Asset[] = [];

export const assetsDatabase: Asset[] = [
    ...originalAssets,
    ...b3Assets,
    ...cryptoAssets,
    ...sp500Assets
];

export const assets = assetsDatabase;
